### ISSUE TITLE
feature: support stream ?

### ISSUE THREAD

**Issue by tst2005** [kikito/sha1.lua#6]
Hello,
If I'm not wrong, the current implementation only support sha1 calculation of finite string.
Then we need to read the whole data into one string.
Is there a way to provide a block by block sha1 calculation ?
We could be able to calculate sha1 of very large file.

Regards,

**Comment by mpeterv** [comment]
Hello!

Yes, this should be possible. Will need to maintain some state after each block is given. Without putting much thought into naming , the Interface could be like this:

```lua
local state = sha1.new()
state:add(some_input) -- Not necessarily a multiple of block size
state:add(some_input)
...
local hex_sha1 = state.sha1()) -- sha1 of all collected inputs in hex
local bin_sha1 = state.binary() -- sha1 of all collected inputs in binary
state:add(some_input) -- Can keep adding inputs
```

**Comment by kikito** [comment]
Since we have decided to [deprecate this repo](https://github.com/kikito/sha1.lua/commit/538192c33cd50eb6403c79f4bc1819c07ada06c8), I'm going to mark this issue as closed.

If you need to continue the conversation, please do so by opening a new issue in @mpeterv's repo: https://github.com/mpeterv/sha1

Thanks!

**Comment by tst2005** [comment]
Ok no problem
